(()=>{'use strict';
const RESULT_API='https://ckiltjhcvxriwjfreqfz.supabase.co/functions/v1/submit-quiz-result';
const CLIENT_VERSION='2026-08-25-ar-v5';
const MODE=new URLSearchParams(location.search).get('mode')==='post'?'post':'full';
const {PRE,GAME,POST}=window.AIHQ_DATA;
const conn=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
const $=id=>document.getElementById(id),stage=$('stage'),v=$('cam'),c=$('cv'),ctx=c.getContext('2d');
const start=$('start'),loading=$('loading'),practicalControls=$('practicalControls'),actions=$('actions'),submitStatus=$('submitStatus'),retrySubmit=$('retrySubmit');
for(let n=1;n<=13;n++){let o=document.createElement('option');o.value=n;o.textContent='ม.4/'+n;$('room').appendChild(o)}for(let n=1;n<=8;n++){let o=document.createElement('option');o.value=n;o.textContent=n;$('gp').appendChild(o)}
if(MODE==='post'){$('flowText').textContent='แบบทดสอบหลังเรียน 10 ข้อ • ใช้ Hand Tracking หรือ Touch/Mouse';$('go').textContent='เปิดกล้องและเริ่ม Post-test ✅'}
let S='START',idx=0,pre=0,post=0,score=0,attempt=0,total=0,first=0,feedback='',feedbackUntil=0,id={},submitState='idle';
let hand=false,lm=null,tx=0,ty=0,cx=0,cy=0,pinch=false,oldPinch=false,grab=null,mouse=false,mgrab=null,control='Touch/Mouse',cards=[],zone={};
const ON=.055,OFF=.078;
function uuidv4(){if(crypto.randomUUID)return crypto.randomUUID();let b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0'));return h.slice(0,4).join('')+'-'+h.slice(4,6).join('')+'-'+h.slice(6,8).join('')+'-'+h.slice(8,10).join('')+'-'+h.slice(10).join('')}
let submissionId=uuidv4();
function W(){return stage.clientWidth}function H(){return stage.clientHeight}function size(){let d=Math.min(devicePixelRatio||1,2);c.width=W()*d;c.height=H()*d;ctx.setTransform(d,0,0,d,0,0);zone={x:W()*.22,y:H()*.79,w:W()*.56,h:H()*.13}}addEventListener('resize',size);size();
function rr(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else{let q=Math.min(r,w/2,h/2);ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q)}}
function panel(x,y,w,h,fill='#0f172acd'){rr(x,y,w,h,20);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle='#ffffff2e';ctx.lineWidth=1;ctx.stroke()}function inside(px,py,r){return px>=r.x&&px<=r.x+r.w&&py>=r.y&&py<=r.y+r.h}
const seg=typeof Intl!=='undefined'&&Intl.Segmenter?new Intl.Segmenter('th',{granularity:'word'}):null;function parts(t){return seg?[...seg.segment(String(t))].map(s=>s.segment):Array.from(String(t))}function lines(t,max){let out=[],line='';for(const p of parts(t)){let z=line+p;if(ctx.measureText(z).width<=max||!line)line=z;else{out.push(line.trim());line=p.trimStart()}}if(line.trim())out.push(line.trim());return out}
function fit(t,cx0,cy0,maxW,maxH,maxF=26,minF=10,weight=800,color='#fff'){ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;let f=maxF,ls=[],lh=0;for(;f>=minF;f--){ctx.font=`${weight} ${f}px sans-serif`;ls=lines(t,maxW);lh=f*1.22;if(ls.length*lh<=maxH)break}if(f<minF){f=minF;ctx.font=`${weight} ${f}px sans-serif`;ls=lines(t,maxW);lh=f*1.15}let ml=Math.max(1,Math.floor(maxH/lh));if(ls.length>ml)ls=ls.slice(0,ml);let sy=cy0-(ls.length-1)*lh/2;ls.forEach((s,i)=>ctx.fillText(s,cx0,sy+i*lh));ctx.textBaseline='alphabetic'}
function dataset(){return S==='PRE'?PRE:S==='POST'?POST:GAME}function q(){return dataset()[idx]}
function loadQ(){let d=q(),mobile=W()<900,g=Math.max(8,W()*.016),cw=(W()*.86-g*2)/3,ch=Math.min(H()*.26,180),x0=W()*.07,y=H()*.39;cards=d[1].map((t,k)=>({t,ok:k===d[2],x:x0+k*(cw+g),y,w:cw,h:ch,ox:x0+k*(cw+g),oy:y})).sort(()=>Math.random()-.5);cards.forEach((o,k)=>{o.x=o.ox=x0+k*(cw+g);o.y=o.oy=y});attempt=0;grab=mgrab=null;feedback=''}
function currentCard(){for(let k=cards.length-1;k>=0;k--)if(inside(cx,cy,cards[k]))return cards[k]}
function answer(o){if(!o)return;if(S==='PRE'||S==='POST'){if(o.ok){if(S==='PRE')pre++;else post++}nextQ();return}attempt++;total++;if(o.ok){score+=Math.max(60,100-(attempt-1)*20);if(attempt===1)first++;feedback='✅ '+q()[3];feedbackUntil=performance.now()+650;setTimeout(nextQ,650)}else{feedback='ลองใหม่ • '+q()[3];feedbackUntil=performance.now()+1000;o.x=o.ox;o.y=o.oy}}
function nextQ(){idx++;if(idx<dataset().length){loadQ();return}idx=0;if(S==='PRE'){S='INTRO'}else if(S==='GAME'){S='PRACTICAL';practicalControls.classList.remove('hidden2')}else if(S==='POST'){S='END';actions.classList.remove('hidden2');setTimeout(submitResult,150)}}
function release(o){if(!o)return;if(inside(o.x+o.w/2,o.y+o.h/2,zone))answer(o);else{o.x=o.ox;o.y=o.oy}}
async function init(){let name=$('nm').value.trim(),no=$('no').value.trim();if(!name){alert('กรุณากรอกชื่อ–สกุล');return}if(!/^\d{1,2}$/.test(no)||Number(no)<1||Number(no)>99){alert('กรุณากรอกเลขที่ให้ถูกต้อง');return}id={name,no:Number(no),room:Number($('room').value),group:Number($('gp').value)};start.classList.add('hidden2');loading.classList.remove('hidden2');try{let h=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});h.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.6,minTrackingConfidence:.6,selfieMode:false});h.onResults(r=>{if(r.multiHandLandmarks&&r.multiHandLandmarks.length){lm=r.multiHandLandmarks[0];hand=true;let a=lm[8],b=lm[4];tx=(1-a.x)*W();ty=a.y*H();let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(!pinch&&d<ON)pinch=true;else if(pinch&&d>OFF)pinch=false}else{lm=null;hand=false;pinch=false}});let cam=new Camera(v,{onFrame:async()=>await h.send({image:v}),width:1280,height:720});await cam.start()}catch(e){console.warn('Camera/Hand Tracking unavailable',e);feedback='⚠️ กล้องไม่พร้อม — ใช้ Touch/Mouse สำรองได้';feedbackUntil=performance.now()+4000}loading.classList.add('hidden2');S=MODE==='post'?'POST':'PRE';idx=0;loadQ()}
$('go').onclick=init;$('postNext').onclick=()=>{practicalControls.classList.add('hidden2');S='POST';idx=0;post=0;loadQ()};
function handAct(){if(!hand||mouse){oldPinch=pinch;return}cx+=(tx-cx)*.32;cy+=(ty-cy)*.32;control='Hand AR';let down=pinch&&!oldPinch,up=!pinch&&oldPinch;if(down){if(S==='INTRO'){S='GAME';idx=0;score=total=first=0;loadQ()}else if(['PRE','GAME','POST'].includes(S))grab=currentCard()||null}if(grab&&pinch){grab.x=cx-grab.w/2;grab.y=cy-grab.h/2}if(up&&grab){release(grab);grab=null}oldPinch=pinch}
function P(e){let r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}c.onpointerdown=e=>{let p=P(e);mouse=true;cx=p.x;cy=p.y;control=e.pointerType==='touch'?'Touch':'Mouse';if(S==='INTRO'){S='GAME';idx=0;score=total=first=0;loadQ()}else if(['PRE','GAME','POST'].includes(S))mgrab=currentCard()||null};c.onpointermove=e=>{let p=P(e);cx=p.x;cy=p.y;if(mouse&&mgrab){mgrab.x=cx-mgrab.w/2;mgrab.y=cy-mgrab.h/2}};c.onpointerup=()=>{if(mgrab){release(mgrab);mgrab=null}mouse=false};
function bg(){if(!v.srcObject){let g=ctx.createLinearGradient(0,0,W(),H());g.addColorStop(0,'#07152e');g.addColorStop(1,'#28114c');ctx.fillStyle=g;ctx.fillRect(0,0,W(),H())}else{ctx.fillStyle='#02061766';ctx.fillRect(0,0,W(),H())}}
function skeleton(){if(!lm)return;ctx.strokeStyle='#22d3ee';ctx.lineWidth=3;for(const [a,b] of conn){ctx.beginPath();ctx.moveTo((1-lm[a].x)*W(),lm[a].y*H());ctx.lineTo((1-lm[b].x)*W(),lm[b].y*H());ctx.stroke()}for(let k=0;k<lm.length;k++){ctx.beginPath();ctx.arc((1-lm[k].x)*W(),lm[k].y*H(),k===4||k===8?6:4,0,Math.PI*2);ctx.fillStyle=k===4||k===8?'#fde047':'#67e8f9';ctx.fill()}}
function cursor(){if(!hand||mouse)return;let h=currentCard();ctx.beginPath();ctx.arc(cx,cy,20,0,Math.PI*2);ctx.lineWidth=4;ctx.strokeStyle=grab?'#22c55e':h?'#fde047':'#38bdf8';if(h&&!grab)ctx.setLineDash([7,6]);ctx.stroke();ctx.setLineDash([])}
function quiz(){let d=q(),mobile=W()<900;panel(W()*.37,10,W()*.26,38);ctx.fillStyle='#fff';ctx.font=`700 ${mobile?12:14}px sans-serif`;ctx.textAlign='center';ctx.fillText(S==='GAME'?`AR Quest ${idx+1}/10  ⭐ ${score}/1000`:S==='PRE'?`Pre-test ${idx+1}/10`:`Post-test ${idx+1}/10`,W()/2,35);let qy=58,qh=Math.max(110,H()*.19);panel(W()*.06,qy,W()*.88,qh);fit(d[0],W()/2,qy+qh/2,W()*.80,qh-22,mobile?21:26,12,850,'#e0f2fe');cards.forEach(o=>{panel(o.x,o.y,o.w,o.h);fit(o.t,o.x+o.w/2,o.y+o.h/2,o.w*.84,o.h*.72,mobile?17:20,10,800,'#fff')});ctx.setLineDash([10,8]);rr(zone.x,zone.y,zone.w,zone.h,22);ctx.strokeStyle='#67e8f9';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);fit('🎯 จีบมือค้างเพื่อลาก แล้วปล่อยคำตอบที่นี่',W()/2,zone.y+zone.h/2,zone.w*.88,zone.h*.68,mobile?15:19,10,800,'#cffafe');if(feedback&&performance.now()<feedbackUntil){panel(W()*.18,H()*.70,W()*.64,H()*.06,'#111827dd');fit(feedback,W()/2,H()*.73,W()*.58,H()*.045,mobile?12:15,9,700,'#fde68a')}}
function intro(){panel(W()*.13,H()*.12,W()*.74,H()*.67);fit('✅ Pre-test ครบแล้ว',W()/2,H()*.23,W()*.66,H()*.10,W()<900?25:36,14,900,'#fff');fit('ต่อไปเป็น AR Quest 10 ด่าน',W()/2,H()*.35,W()*.62,H()*.08,W()<900?20:27,12,900,'#67e8f9');fit('ใช้ “จีบนิ้วโป้ง + นิ้วชี้” เพื่อหยิบคำตอบ แล้วลากลงพื้นที่เป้าหมาย',W()/2,H()*.47,W()*.70,H()*.13,W()<900?15:20,10,700,'#e2e8f0');fit('หรือแตะ/ลากด้วย Touch และ Mouse ได้',W()/2,H()*.59,W()*.62,H()*.07,W()<900?13:17,10,700,'#cbd5e1');fit('จีบมือ หรือแตะหน้าจอ เพื่อเริ่ม',W()/2,H()*.69,W()*.58,H()*.08,W()<900?16:21,11,900,'#86efac')}
function practical(){panel(W()*.055,H()*.055,W()*.89,H()*.82);fit('🔎 Explore 3 Stations + Mentimeter',W()/2,H()*.13,W()*.78,H()*.07,W()<900?21:30,13,900,'#fff');fit('ลงมือสำรวจจริงก่อนสังเคราะห์ข้อค้นพบท้าย Explore',W()/2,H()*.19,W()*.76,H()*.05,W()<900?12:16,9,700,'#a5f3fc');let a=[['🧠 Station A — AI / Browser','Webcam • Prediction • Hand/No Hand • ความเสถียร'],['💡 Station B — ESP32 / Output','Web Server • /on /off • GPIO • Output'],['🔗 Station C — Integration','Webcam → Browser/AI → HTTP → ESP32 → Output'],['🤝 Peer Teaching','อธิบายหลักฐานและจุดที่ทำงานแล้ว/ยังต้องตรวจ']];a.forEach((z,k)=>{let xx=k%2?W()*.51:W()*.09,yy=k<2?H()*.27:H()*.49;panel(xx,yy,W()*.40,H()*.16);ctx.textAlign='left';ctx.fillStyle='#fde68a';ctx.font=`800 ${W()<900?13:17}px sans-serif`;ctx.fillText(z[0],xx+14,yy+31);fit(z[1],xx+W()*.20,yy+H()*.105,W()*.35,H()*.07,W()<900?11:14,9,650,'#e2e8f0')});fit('ท้าย Explore: Mentimeter • รหัส 7812 2870',W()/2,H()*.715,W()*.75,H()*.06,W()<900?15:20,11,900,'#ddd6fe');fit('กดปุ่มด้านล่างเพื่อเปิด Mentimeter แล้วกลับมาทำ Post-test',W()/2,H()*.765,W()*.75,H()*.05,W()<900?11:14,9,650,'#cbd5e1')}
function end(){let pct=Math.round(post/POST.length*100),passed=pct>=70,prePct=Math.round(pre/PRE.length*100),gain=pct-prePct;panel(W()*.08,H()*.07,W()*.84,H()*.76);fit('🎉 สรุปผลการเรียนรู้',W()/2,H()*.16,W()*.72,H()*.08,W()<900?23:34,14,900,'#fde68a');fit(`${id.name} • เลขที่ ${id.no} • ม.4/${id.room} • กลุ่ม ${id.group}`,W()/2,H()*.23,W()*.72,H()*.06,W()<900?12:16,9,700,'#fff');if(MODE!=='post'){fit(`Pre ${pre}/10 (${prePct}%)`,W()*.30,H()*.35,W()*.30,H()*.08,W()<900?17:23,11,900,'#fbbf24');fit(`Post ${post}/10 (${pct}%)`,W()*.70,H()*.35,W()*.30,H()*.08,W()<900?17:23,11,900,'#86efac');fit(`พัฒนาการ ${gain>=0?'+':''}${gain} จุดเปอร์เซ็นต์`,W()/2,H()*.46,W()*.60,H()*.06,W()<900?14:18,10,800,'#67e8f9');fit(`AR Quest ${score}/1000 • ถูกครั้งแรก ${first}/10`,W()/2,H()*.55,W()*.68,H()*.06,W()<900?13:17,10,700,'#c4b5fd')}else fit(`Post-test ${post}/10 (${pct}%)`,W()/2,H()*.39,W()*.62,H()*.10,W()<900?27:36,16,900,'#86efac');fit(passed?'✅ ผ่านเกณฑ์ 7/10':'❌ ยังไม่ผ่านเกณฑ์ 7/10',W()/2,H()*.65,W()*.66,H()*.09,W()<900?24:34,15,900,passed?'#86efac':'#fca5a5');fit('ผลจะถูกส่งเข้า Teacher Dashboard อัตโนมัติ',W()/2,H()*.74,W()*.70,H()*.05,W()<900?12:15,9,650,'#cbd5e1')}
async function submitResult(){if(submitState==='sending'||submitState==='sent')return;submitState='sending';submitStatus.textContent='⏳ กำลังส่งผลเข้าระบบครู...';retrySubmit.classList.add('hidden2');try{let payload={submission_id:submissionId,mode:MODE,name:id.name,student_no:id.no,room:id.room,group_no:id.group,pre_score:MODE==='post'?null:pre,post_score:post,game_score:MODE==='post'?0:score,first_try:MODE==='post'?0:first,attempts:MODE==='post'?0:total,control,client_version:CLIENT_VERSION};let r=await fetch(RESULT_API,{method:'POST',headers:{'Content-Type':'application/json','x-client-version':CLIENT_VERSION},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw Error(j.error||'ส่งผลไม่สำเร็จ');submitState='sent';submitStatus.textContent=j.duplicate?'✅ ผลนี้ถูกบันทึกไว้แล้ว':'✅ บันทึกผลเข้าระบบครูแล้ว'}catch(e){console.error(e);submitState='error';submitStatus.textContent='⚠️ ส่งผลไม่สำเร็จ กรุณาตรวจอินเทอร์เน็ต';retrySubmit.classList.remove('hidden2')}}retrySubmit.onclick=submitResult;
function loop(){ctx.clearRect(0,0,W(),H());bg();handAct();if(['PRE','GAME','POST'].includes(S))quiz();else if(S==='INTRO')intro();else if(S==='PRACTICAL')practical();else if(S==='END')end();skeleton();cursor();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
